apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sen8j91gs-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sen8j91gs-java-quarkus-gitops